apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  lables:
    app: gateway
spec:
  replicas: 2
  selectors:
    matchLables:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      lables:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: alirezar80/gateway
          ports:
            containerPort: 9000
          envForm:
            - configMapRef:
                name: gateway-configmap
            - secretRef:
                name: gateway-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
