apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  lable:
    app: auth
spec:
  replicas: 2
  selectors:
    matchLables:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 3
  template:
    metadata:
      lables:
        app: auth
    spec:
      containers:
        - name: auth
          image: alirezar80/auth
          ports:
            - containerPort: 8000
          envForm:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
